# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Test Forum

# Short description (goes below the title; it will also be used in the RSS feed)
description: Forum created in Disqus

# Your name, as you want it to appear underneath each post and in the footer
author: Abhisek Mohanty

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
baseurl:  http://abhisekabove.github.io/forum.

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://klcodanr.github.io/Jekyll-Disqus-Forum

# Exclude system files
exclude: [.gitignore]

# The disqus shortname for your forum
disqus_shortname: mytest1234

# The public key for your disqus application
disqus_publickey: 61bLGtaUogJZEUHgpQ38IfWlZ5NCvQJFFHK9uEnKs69NSW7Ft8Tvmsdo0d0Ei6CO
